# Generated by Django 5.2 on 2025-04-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uz_word', models.CharField(help_text='The word in Uzbek', max_length=200)),
                ('kh_word', models.CharField(help_text='The translation in Khorezm', max_length=200)),
            ],
        ),
    ]
