# Generated by Django 5.2 on 2025-04-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='description',
            field=models.CharField(blank=True, default='Bogotdo ishlatiladi', help_text="So'z ma'nosi, izohi yoki qo'shimcha ma'lumot", max_length=250),
        ),
        migrations.AlterField(
            model_name='translation',
            name='kh_word',
            field=models.CharField(help_text='Xorazm tarjimasi', max_length=200),
        ),
        migrations.AlterField(
            model_name='translation',
            name='uz_word',
            field=models.CharField(help_text="O'zbek so'zi", max_length=200),
        ),
    ]
